# One Hot Encoding

## Importing Libraries

In [1]:
import numpy as np 
import pandas as pd

### Using Scaled Data

In [3]:
df = pd.read_csv(r"C:\Users\FARJAD FARHAT\Downloads\MLProject\Phase1\scaledDelay.csv")

In [4]:
df.head(5)

,Flight Number,Type,Status,Departure IATA Code,Departure ICAO Code,Scheduled Time,Actual Time,Arrival IATA Code,Arrival ICAO Code,Arrival Estimated Time,...,Humidity (%)Max,Humidity (%)avg,Humidity (%)Min,Wind Speed (mph)Max,Wind Speed (mph)avg,Wind Speed (mph)Min,Pressure (in)Max,Pressure (in)avg,Pressure (in)Min,departure_delay
0,737,departure,active,lhe,opla,2023-07-20 20:50:00,2023-07-20 20:15:00,ruh,oerk,2023-07-20 21:54:00,...,0.531856,0.827797,1.089088,-0.329007,-0.095441,-0.345092,-0.897460,-0.454550,0.269328,0.000000
1,843,departure,active,lhe,opla,2023-07-18 15:05:00,NaN,khi,opkc,NaN,...,0.180001,0.691515,1.089088,0.068143,1.164024,-0.345092,-1.337505,-0.454550,0.269328,0.000000
2,841,departure,active,lhe,opla,2023-07-23 09:50:00,NaN,khi,opkc,NaN,...,0.109630,0.530455,0.709605,-0.170147,0.624254,-0.345092,-0.457415,-0.180812,0.281751,0.000000
3,205,departure,active,lhe,opla,2023-07-26 23:30:00,2023-07-26 23:51:00,kwi,okkk,2023-07-27 01:24:00,...,1.305935,0.914521,0.872240,0.068143,0.624254,-0.345092,-0.897460,-0.180812,0.281751,0.855338
4,723,departure,active,lhe,opla,2023-07-20 11:35:00,NaN,dxb,omdb,NaN,...,0.531856,0.827797,1.089088,-0.329007,-0.095441,-0.345092,-0.897460,-0.454550,0.269328,0.000000

In [5]:
categorical_cols = ['Type', 'Status','Departure IATA Code', 'Departure ICAO Code','Days', 'Month', 'Year', 'Hour']
df[categorical_cols] = df[categorical_cols].fillna('unknown')
df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

In [6]:
features = ['Temperature (°F)avg','Temperature (°F)Max','Temperature (°F)Min','Humidity (%)avg','Humidity (%)Max','Humidity (%)Min',
'Wind Speed (mph)avg','Wind Speed (mph)Max','Wind Speed (mph)Min', 'Pressure (in)avg', 'Pressure (in)Max', 'Pressure (in)Min',
'Dew Point (°F)Max', 'Dew Point (°F)avg', 'Dew Point (°F)Min'
] + [col for col in df.columns if 'Departure IATA Code' in col or 'Departure ICAO Code' in col or 'Month' in col or 'Year' in col or 'status'
in col or 'Days' in col or 'Hour' in col]

X = df[features]  
y = df['departure_delay']

In [7]:
temp = df[features + ['departure_delay']]

In [8]:
temp.to_csv('TrainModelDataFinalScl.csv', index=False)

## Using Not Scaled Data

In [11]:
df = pd.read_csv(r"C:\Users\FARJAD FARHAT\Downloads\MLProject\Phase1\NotScaledDelay.csv")

In [12]:
df.head(5)

,Flight Number,Type,Status,Departure IATA Code,Departure ICAO Code,Scheduled Time,Actual Time,Arrival IATA Code,Arrival ICAO Code,Arrival Estimated Time,...,Humidity (%)Max,Humidity (%)avg,Humidity (%)Min,Wind Speed (mph)Max,Wind Speed (mph)avg,Wind Speed (mph)Min,Pressure (in)Max,Pressure (in)avg,Pressure (in)Min,departure_delay
0,737,departure,active,lhe,opla,2023-07-20 20:50:00,2023-07-20 20:15:00,ruh,oerk,2023-07-20 21:54:00,...,0.531856,0.827797,1.089088,-0.329007,-0.095441,-0.345092,-0.897460,-0.454550,0.269328,0.00
1,843,departure,active,lhe,opla,2023-07-18 15:05:00,NaN,khi,opkc,NaN,...,0.180001,0.691515,1.089088,0.068143,1.164024,-0.345092,-1.337505,-0.454550,0.269328,13.48
2,841,departure,active,lhe,opla,2023-07-23 09:50:00,NaN,khi,opkc,NaN,...,0.109630,0.530455,0.709605,-0.170147,0.624254,-0.345092,-0.457415,-0.180812,0.281751,13.48
3,205,departure,active,lhe,opla,2023-07-26 23:30:00,2023-07-26 23:51:00,kwi,okkk,2023-07-27 01:24:00,...,1.305935,0.914521,0.872240,0.068143,0.624254,-0.345092,-0.897460,-0.180812,0.281751,21.00
4,723,departure,active,lhe,opla,2023-07-20 11:35:00,NaN,dxb,omdb,NaN,...,0.531856,0.827797,1.089088,-0.329007,-0.095441,-0.345092,-0.897460,-0.454550,0.269328,13.48

In [13]:
categorical_cols = ['Type', 'Status','Departure IATA Code', 'Departure ICAO Code','Days', 'Month', 'Year', 'Hour']
df[categorical_cols] = df[categorical_cols].fillna('unknown')
df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

In [14]:
features = ['Temperature (°F)avg','Temperature (°F)Max','Temperature (°F)Min','Humidity (%)avg','Humidity (%)Max','Humidity (%)Min',
'Wind Speed (mph)avg','Wind Speed (mph)Max','Wind Speed (mph)Min', 'Pressure (in)avg', 'Pressure (in)Max', 'Pressure (in)Min',
'Dew Point (°F)Max', 'Dew Point (°F)avg', 'Dew Point (°F)Min'
] + [col for col in df.columns if 'Departure IATA Code' in col or 'Departure ICAO Code' in col or 'Month' in col or 'Year' in col or 'status'
in col or 'Days' in col or 'Hour' in col]

X = df[features]  
y = df['departure_delay']

In [15]:
temp = df[features + ['departure_delay']]

In [16]:
temp.to_csv('TrainModelDataFinalNotScl.csv', index=False)

## Test Data

In [17]:
df = pd.read_csv(r"C:\Users\FARJAD FARHAT\Downloads\MLProject\Phase1\MergedTestData.csv")

In [18]:
df.head(5)

,Flight Number,Type,Status,Departure IATA Code,Departure ICAO Code,Scheduled Time,Arrival IATA Code,Arrival ICAO Code,Arrival Estimated Time,Days,...,Dew Point (°F)Min,Humidity (%)Max,Humidity (%)avg,Humidity (%)Min,Wind Speed (mph)Max,Wind Speed (mph)avg,Wind Speed (mph)Min,Pressure (in)Max,Pressure (in)avg,Pressure (in)Min
0,4361,departure,active,lhe,opla,2024-05-14 00:20:00,dxb,omdb,2024-05-14 00:20:00,14,...,-0.204773,-1.931125,-1.823500,-1.350446,0.544722,0.598550,-0.345092,-0.017370,0.092927,0.306598
1,1876,departure,active,lhe,opla,2024-05-07 04:15:00,ruh,oerk,2024-05-07 04:15:00,7,...,-0.663270,-1.931125,-1.953587,-1.621505,-0.170147,-0.301068,-0.345092,-0.457415,-0.180812,0.294175
2,6030,departure,active,lhe,opla,2024-05-09 03:10:00,doh,othh,2024-05-09 03:10:00,9,...,0.253725,-1.368158,-1.247401,-0.862539,0.306432,0.649957,-0.345092,-0.897460,-0.180812,0.281751
3,739,departure,active,lhe,opla,2024-05-12 02:50:00,jed,oejn,2024-05-12 02:50:00,12,...,0.384724,0.109630,-0.522630,-0.483056,0.544722,1.241134,1.662075,-0.017370,0.366666,0.294175
4,3932,departure,active,lhe,opla,2024-05-16 04:35:00,auh,omaa,2024-05-16 04:35:00,16,...,0.122726,-2.142238,-1.817306,-1.296234,-0.567297,-0.455288,-0.345092,-0.017370,0.092927,0.294175

In [19]:
categorical_cols = ['Type', 'Status','Departure IATA Code', 'Departure ICAO Code','Days', 'Month', 'Year', 'Hour']
df[categorical_cols] = df[categorical_cols].fillna('unknown')
df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

In [20]:
features = ['Temperature (°F)avg','Temperature (°F)Max','Temperature (°F)Min','Humidity (%)avg','Humidity (%)Max','Humidity (%)Min',
'Wind Speed (mph)avg','Wind Speed (mph)Max','Wind Speed (mph)Min', 'Pressure (in)avg', 'Pressure (in)Max', 'Pressure (in)Min',
'Dew Point (°F)Max', 'Dew Point (°F)avg', 'Dew Point (°F)Min'
] + [col for col in df.columns if 'Departure IATA Code' in col or 'Departure ICAO Code' in col or 'Month' in col or 'Year' in col or 'status'
in col or 'Days' in col or 'Hour' in col]

X = df[features]

In [21]:
X.to_csv('TestModelDataFinal.csv', index=False)