In [1]:
import pandas as pd 
import numpy as np
import os
from sklearn.preprocessing import StandardScaler

In [2]:
def get_filenames(directory):
    filenames = os.listdir(directory)    
    return filenames

In [5]:
basePath = r'C:\Users\FARJAD FARHAT\Downloads\MLProject\Phase1\Weather_Months'
names = get_filenames(basePath)

In [6]:
dfs = []
for i in names:
    df = pd.read_csv(os.path.join(basePath,i))
    df['Month'] = i[0:3]
    if "2024" in i:
        df['Year'] = "2024"
    else:
        df['Year'] = "2023"
    dfs.append(df)
df = pd.concat(dfs,axis=0,ignore_index=True)

In [7]:
scale = StandardScaler()
for col in df.columns[1:16]:
    df[col] = scale.fit_transform(df[col].values.reshape(-1,1))
df

,Days,Temperature (°F)Max,Temperature (°F)avg,Temperature (°F)Min,Dew Point (°F)Max,Dew Point (°F)avg,Dew Point (°F)Min,Humidity (%)Max,Humidity (%)avg,Humidity (%)Min,Wind Speed (mph)Max,Wind Speed (mph)avg,Wind Speed (mph)Min,Pressure (in)Max,Pressure (in)avg,Pressure (in)Min,Month,Year
0,1,0.023176,-0.077997,0.050275,-0.090039,-0.681696,-0.597770,-0.945933,-0.937670,-0.970963,0.147572,0.958397,1.662075,-0.017370,0.366666,0.306598,Apr,2024
1,2,0.282207,0.102933,-0.064124,-0.435643,-0.673349,-0.794269,0.109630,-1.049173,-1.242022,-0.329007,0.110186,-0.345092,-0.457415,0.092927,0.294175,Apr,2024
2,3,0.346965,0.149840,0.050275,-0.608445,-0.422927,-0.335772,-0.594078,-0.919086,-0.916751,-0.170147,-0.121144,-0.345092,-0.017370,0.092927,0.306598,Apr,2024
3,4,0.346965,0.210151,0.050275,-0.435643,-0.564833,-0.335772,-1.227416,-1.197844,-1.025175,0.147572,0.804177,-0.345092,-0.017370,0.366666,0.306598,Apr,2024
4,5,0.346965,0.290564,0.050275,-0.781247,-0.932118,-0.794269,-1.227416,-1.600494,-1.350446,-0.011287,0.932694,-0.345092,-0.017370,0.092927,0.306598,Apr,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,26,0.346965,0.417885,0.565071,0.773971,0.837529,0.843222,0.531856,0.387979,0.167486,-0.329007,-0.583805,-0.345092,-0.017370,0.092927,0.306598,Sep,2023
376,27,0.476480,0.498299,0.450672,0.687570,0.678929,0.712222,0.109630,-0.039450,-0.103573,-0.329007,-0.558101,-0.345092,-0.017370,0.092927,0.294175,Sep,2023
377,28,0.605995,0.672528,0.565071,0.946773,0.987782,0.974221,0.531856,0.084442,0.221698,-0.805587,-0.866542,-0.345092,-0.457415,0.092927,0.294175,Sep,2023
378,29,0.605995,0.538505,0.565071,0.773971,0.904308,0.843222,0.109630,0.220724,-0.103573,-0.170147,-0.403881,-0.345092,-0.017370,0.092927,0.294175,Sep,2023
379,30,0.476480,0.424586,0.450672,0.514768,0.478591,0.581223,-0.242224,-0.169537,-0.266209,-0.329007,0.161593,-0.345092,-0.017370,0.092927,0.294175,Sep,2023

In [8]:
Traindf = pd.read_csv("Train.csv")
Traindf["Year"] = Traindf["Year"].astype(str)

In [9]:
result = pd.merge(Traindf, df, on=["Days", "Month","Year"], how="inner", suffixes=("_df1", "_df2"))

In [10]:
print(result.isnull().sum())

Flight Number                 0
Type                          0
Status                        0
Departure IATA Code           0
Departure ICAO Code           0
Scheduled Time                0
Actual Time               20582
Arrival IATA Code             0
Arrival ICAO Code             0
Arrival Estimated Time    21364
Days                          0
Month                         0
Year                          0
Hour                          0
Temperature (°F)Max           0
Temperature (°F)avg           0
Temperature (°F)Min           0
Dew Point (°F)Max             0
Dew Point (°F)avg             0
Dew Point (°F)Min             0
Humidity (%)Max               0
Humidity (%)avg               0
Humidity (%)Min               0
Wind Speed (mph)Max           0
Wind Speed (mph)avg           0
Wind Speed (mph)Min           0
Pressure (in)Max              0
Pressure (in)avg              0
Pressure (in)Min              0
dtype: int64

In [11]:
result['Scheduled Time'] = pd.to_datetime(result['Scheduled Time'], errors='coerce')
result['Actual Time'] = pd.to_datetime(result['Actual Time'], errors='coerce')

result['departure_delay'] = np.where(
    result['Actual Time'].notna() & result['Scheduled Time'].notna(),
    (result['Actual Time'] - result['Scheduled Time']).dt.total_seconds() / 60, 
    np.nan  
)

result

,Flight Number,Type,Status,Departure IATA Code,Departure ICAO Code,Scheduled Time,Actual Time,Arrival IATA Code,Arrival ICAO Code,Arrival Estimated Time,...,Humidity (%)Max,Humidity (%)avg,Humidity (%)Min,Wind Speed (mph)Max,Wind Speed (mph)avg,Wind Speed (mph)Min,Pressure (in)Max,Pressure (in)avg,Pressure (in)Min,departure_delay
0,737,departure,active,lhe,opla,2023-07-20 20:50:00,2023-07-20 20:15:00,ruh,oerk,2023-07-20 21:54:00,...,0.531856,0.827797,1.089088,-0.329007,-0.095441,-0.345092,-0.897460,-0.454550,0.269328,-35.0
1,843,departure,active,lhe,opla,2023-07-18 15:05:00,NaT,khi,opkc,NaN,...,0.180001,0.691515,1.089088,0.068143,1.164024,-0.345092,-1.337505,-0.454550,0.269328,NaN
2,841,departure,active,lhe,opla,2023-07-23 09:50:00,NaT,khi,opkc,NaN,...,0.109630,0.530455,0.709605,-0.170147,0.624254,-0.345092,-0.457415,-0.180812,0.281751,NaN
3,205,departure,active,lhe,opla,2023-07-26 23:30:00,2023-07-26 23:51:00,kwi,okkk,2023-07-27 01:24:00,...,1.305935,0.914521,0.872240,0.068143,0.624254,-0.345092,-0.897460,-0.180812,0.281751,21.0
4,723,departure,active,lhe,opla,2023-07-20 11:35:00,NaT,dxb,omdb,NaN,...,0.531856,0.827797,1.089088,-0.329007,-0.095441,-0.345092,-0.897460,-0.454550,0.269328,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51567,841,departure,active,lhe,opla,2023-11-16 09:50:00,2023-11-16 10:03:00,khi,opkc,2023-11-16 11:34:00,...,0.039260,0.177362,-0.049361,-0.726157,-1.252092,-0.345092,1.302765,0.914143,0.343869,13.0
51568,735,departure,active,lhe,opla,2023-11-16 11:40:00,2023-11-16 11:48:00,jed,oejn,2023-11-16 14:48:00,...,0.039260,0.177362,-0.049361,-0.726157,-1.252092,-0.345092,1.302765,0.914143,0.343869,8.0
51569,203,departure,active,lhe,opla,2023-11-27 10:50:00,NaT,dxb,omdb,NaN,...,0.461485,0.728683,0.926452,-0.329007,-0.866542,-0.345092,0.862720,0.914143,0.331445,NaN
51570,898,departure,active,lhe,opla,2023-11-19 02:00:00,NaT,kul,wmkk,NaN,...,0.461485,0.226919,-0.049361,-0.646727,-1.072169,-0.345092,1.302765,-0.728289,-3.296211,NaN
51571,731,departure,active,lhe,opla,2023-11-23 06:30:00,2023-11-23 06:47:00,jed,oejn,2023-11-23 10:00:00,...,0.461485,0.412757,-2.326259,-0.805587,-1.277796,-0.345092,0.422675,-1.002027,-3.296211,17.0

In [12]:
result.loc[result['departure_delay'] < 0, 'departure_delay'] = 0
result

,Flight Number,Type,Status,Departure IATA Code,Departure ICAO Code,Scheduled Time,Actual Time,Arrival IATA Code,Arrival ICAO Code,Arrival Estimated Time,...,Humidity (%)Max,Humidity (%)avg,Humidity (%)Min,Wind Speed (mph)Max,Wind Speed (mph)avg,Wind Speed (mph)Min,Pressure (in)Max,Pressure (in)avg,Pressure (in)Min,departure_delay
0,737,departure,active,lhe,opla,2023-07-20 20:50:00,2023-07-20 20:15:00,ruh,oerk,2023-07-20 21:54:00,...,0.531856,0.827797,1.089088,-0.329007,-0.095441,-0.345092,-0.897460,-0.454550,0.269328,0.0
1,843,departure,active,lhe,opla,2023-07-18 15:05:00,NaT,khi,opkc,NaN,...,0.180001,0.691515,1.089088,0.068143,1.164024,-0.345092,-1.337505,-0.454550,0.269328,NaN
2,841,departure,active,lhe,opla,2023-07-23 09:50:00,NaT,khi,opkc,NaN,...,0.109630,0.530455,0.709605,-0.170147,0.624254,-0.345092,-0.457415,-0.180812,0.281751,NaN
3,205,departure,active,lhe,opla,2023-07-26 23:30:00,2023-07-26 23:51:00,kwi,okkk,2023-07-27 01:24:00,...,1.305935,0.914521,0.872240,0.068143,0.624254,-0.345092,-0.897460,-0.180812,0.281751,21.0
4,723,departure,active,lhe,opla,2023-07-20 11:35:00,NaT,dxb,omdb,NaN,...,0.531856,0.827797,1.089088,-0.329007,-0.095441,-0.345092,-0.897460,-0.454550,0.269328,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51567,841,departure,active,lhe,opla,2023-11-16 09:50:00,2023-11-16 10:03:00,khi,opkc,2023-11-16 11:34:00,...,0.039260,0.177362,-0.049361,-0.726157,-1.252092,-0.345092,1.302765,0.914143,0.343869,13.0
51568,735,departure,active,lhe,opla,2023-11-16 11:40:00,2023-11-16 11:48:00,jed,oejn,2023-11-16 14:48:00,...,0.039260,0.177362,-0.049361,-0.726157,-1.252092,-0.345092,1.302765,0.914143,0.343869,8.0
51569,203,departure,active,lhe,opla,2023-11-27 10:50:00,NaT,dxb,omdb,NaN,...,0.461485,0.728683,0.926452,-0.329007,-0.866542,-0.345092,0.862720,0.914143,0.331445,NaN
51570,898,departure,active,lhe,opla,2023-11-19 02:00:00,NaT,kul,wmkk,NaN,...,0.461485,0.226919,-0.049361,-0.646727,-1.072169,-0.345092,1.302765,-0.728289,-3.296211,NaN
51571,731,departure,active,lhe,opla,2023-11-23 06:30:00,2023-11-23 06:47:00,jed,oejn,2023-11-23 10:00:00,...,0.461485,0.412757,-2.326259,-0.805587,-1.277796,-0.345092,0.422675,-1.002027,-3.296211,17.0

In [13]:
result['departure_delay'] = result['departure_delay'].fillna(result['departure_delay'].mean()).round(2)
result

,Flight Number,Type,Status,Departure IATA Code,Departure ICAO Code,Scheduled Time,Actual Time,Arrival IATA Code,Arrival ICAO Code,Arrival Estimated Time,...,Humidity (%)Max,Humidity (%)avg,Humidity (%)Min,Wind Speed (mph)Max,Wind Speed (mph)avg,Wind Speed (mph)Min,Pressure (in)Max,Pressure (in)avg,Pressure (in)Min,departure_delay
0,737,departure,active,lhe,opla,2023-07-20 20:50:00,2023-07-20 20:15:00,ruh,oerk,2023-07-20 21:54:00,...,0.531856,0.827797,1.089088,-0.329007,-0.095441,-0.345092,-0.897460,-0.454550,0.269328,0.00
1,843,departure,active,lhe,opla,2023-07-18 15:05:00,NaT,khi,opkc,NaN,...,0.180001,0.691515,1.089088,0.068143,1.164024,-0.345092,-1.337505,-0.454550,0.269328,13.48
2,841,departure,active,lhe,opla,2023-07-23 09:50:00,NaT,khi,opkc,NaN,...,0.109630,0.530455,0.709605,-0.170147,0.624254,-0.345092,-0.457415,-0.180812,0.281751,13.48
3,205,departure,active,lhe,opla,2023-07-26 23:30:00,2023-07-26 23:51:00,kwi,okkk,2023-07-27 01:24:00,...,1.305935,0.914521,0.872240,0.068143,0.624254,-0.345092,-0.897460,-0.180812,0.281751,21.00
4,723,departure,active,lhe,opla,2023-07-20 11:35:00,NaT,dxb,omdb,NaN,...,0.531856,0.827797,1.089088,-0.329007,-0.095441,-0.345092,-0.897460,-0.454550,0.269328,13.48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51567,841,departure,active,lhe,opla,2023-11-16 09:50:00,2023-11-16 10:03:00,khi,opkc,2023-11-16 11:34:00,...,0.039260,0.177362,-0.049361,-0.726157,-1.252092,-0.345092,1.302765,0.914143,0.343869,13.00
51568,735,departure,active,lhe,opla,2023-11-16 11:40:00,2023-11-16 11:48:00,jed,oejn,2023-11-16 14:48:00,...,0.039260,0.177362,-0.049361,-0.726157,-1.252092,-0.345092,1.302765,0.914143,0.343869,8.00
51569,203,departure,active,lhe,opla,2023-11-27 10:50:00,NaT,dxb,omdb,NaN,...,0.461485,0.728683,0.926452,-0.329007,-0.866542,-0.345092,0.862720,0.914143,0.331445,13.48
51570,898,departure,active,lhe,opla,2023-11-19 02:00:00,NaT,kul,wmkk,NaN,...,0.461485,0.226919,-0.049361,-0.646727,-1.072169,-0.345092,1.302765,-0.728289,-3.296211,13.48
51571,731,departure,active,lhe,opla,2023-11-23 06:30:00,2023-11-23 06:47:00,jed,oejn,2023-11-23 10:00:00,...,0.461485,0.412757,-2.326259,-0.805587,-1.277796,-0.345092,0.422675,-1.002027,-3.296211,17.00

In [14]:
result.to_csv("NotScaledDelay.csv",index=False)

In [15]:
result['departure_delay'] = scale.fit_transform(result['departure_delay'].values.reshape(-1,1))

In [16]:
result.loc[result['departure_delay'] < 0, 'departure_delay'] = 0
result

,Flight Number,Type,Status,Departure IATA Code,Departure ICAO Code,Scheduled Time,Actual Time,Arrival IATA Code,Arrival ICAO Code,Arrival Estimated Time,...,Humidity (%)Max,Humidity (%)avg,Humidity (%)Min,Wind Speed (mph)Max,Wind Speed (mph)avg,Wind Speed (mph)Min,Pressure (in)Max,Pressure (in)avg,Pressure (in)Min,departure_delay
0,737,departure,active,lhe,opla,2023-07-20 20:50:00,2023-07-20 20:15:00,ruh,oerk,2023-07-20 21:54:00,...,0.531856,0.827797,1.089088,-0.329007,-0.095441,-0.345092,-0.897460,-0.454550,0.269328,0.000000
1,843,departure,active,lhe,opla,2023-07-18 15:05:00,NaT,khi,opkc,NaN,...,0.180001,0.691515,1.089088,0.068143,1.164024,-0.345092,-1.337505,-0.454550,0.269328,0.000000
2,841,departure,active,lhe,opla,2023-07-23 09:50:00,NaT,khi,opkc,NaN,...,0.109630,0.530455,0.709605,-0.170147,0.624254,-0.345092,-0.457415,-0.180812,0.281751,0.000000
3,205,departure,active,lhe,opla,2023-07-26 23:30:00,2023-07-26 23:51:00,kwi,okkk,2023-07-27 01:24:00,...,1.305935,0.914521,0.872240,0.068143,0.624254,-0.345092,-0.897460,-0.180812,0.281751,0.855338
4,723,departure,active,lhe,opla,2023-07-20 11:35:00,NaT,dxb,omdb,NaN,...,0.531856,0.827797,1.089088,-0.329007,-0.095441,-0.345092,-0.897460,-0.454550,0.269328,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51567,841,departure,active,lhe,opla,2023-11-16 09:50:00,2023-11-16 10:03:00,khi,opkc,2023-11-16 11:34:00,...,0.039260,0.177362,-0.049361,-0.726157,-1.252092,-0.345092,1.302765,0.914143,0.343869,0.000000
51568,735,departure,active,lhe,opla,2023-11-16 11:40:00,2023-11-16 11:48:00,jed,oejn,2023-11-16 14:48:00,...,0.039260,0.177362,-0.049361,-0.726157,-1.252092,-0.345092,1.302765,0.914143,0.343869,0.000000
51569,203,departure,active,lhe,opla,2023-11-27 10:50:00,NaT,dxb,omdb,NaN,...,0.461485,0.728683,0.926452,-0.329007,-0.866542,-0.345092,0.862720,0.914143,0.331445,0.000000
51570,898,departure,active,lhe,opla,2023-11-19 02:00:00,NaT,kul,wmkk,NaN,...,0.461485,0.226919,-0.049361,-0.646727,-1.072169,-0.345092,1.302765,-0.728289,-3.296211,0.000000
51571,731,departure,active,lhe,opla,2023-11-23 06:30:00,2023-11-23 06:47:00,jed,oejn,2023-11-23 10:00:00,...,0.461485,0.412757,-2.326259,-0.805587,-1.277796,-0.345092,0.422675,-1.002027,-3.296211,0.400205

In [17]:
result.to_csv("scaledDelay.csv",index=False)

In [18]:
df2 = pd.read_csv("Test.csv")

In [19]:
df2['Year'] = df2['Year'].astype(str)

In [20]:
result2 = pd.merge(df2, df, on=["Days", "Month","Year"], how="inner", suffixes=("_df1", "_df2"))

In [21]:
result2

,Flight Number,Type,Status,Departure IATA Code,Departure ICAO Code,Scheduled Time,Arrival IATA Code,Arrival ICAO Code,Arrival Estimated Time,Days,...,Dew Point (°F)Min,Humidity (%)Max,Humidity (%)avg,Humidity (%)Min,Wind Speed (mph)Max,Wind Speed (mph)avg,Wind Speed (mph)Min,Pressure (in)Max,Pressure (in)avg,Pressure (in)Min
0,4361,departure,active,lhe,opla,2024-05-14 00:20:00,dxb,omdb,2024-05-14 00:20:00,14,...,-0.204773,-1.931125,-1.823500,-1.350446,0.544722,0.598550,-0.345092,-0.017370,0.092927,0.306598
1,1876,departure,active,lhe,opla,2024-05-07 04:15:00,ruh,oerk,2024-05-07 04:15:00,7,...,-0.663270,-1.931125,-1.953587,-1.621505,-0.170147,-0.301068,-0.345092,-0.457415,-0.180812,0.294175
2,6030,departure,active,lhe,opla,2024-05-09 03:10:00,doh,othh,2024-05-09 03:10:00,9,...,0.253725,-1.368158,-1.247401,-0.862539,0.306432,0.649957,-0.345092,-0.897460,-0.180812,0.281751
3,739,departure,active,lhe,opla,2024-05-12 02:50:00,jed,oejn,2024-05-12 02:50:00,12,...,0.384724,0.109630,-0.522630,-0.483056,0.544722,1.241134,1.662075,-0.017370,0.366666,0.294175
4,3932,departure,active,lhe,opla,2024-05-16 04:35:00,auh,omaa,2024-05-16 04:35:00,16,...,0.122726,-2.142238,-1.817306,-1.296234,-0.567297,-0.455288,-0.345092,-0.017370,0.092927,0.294175
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12909,615,departure,active,isb,opis,2024-06-23 09:30:00,doh,othh,2024-06-23 09:30:00,23,...,0.515723,-1.368158,-1.371293,-0.916751,-0.170147,-0.044034,-0.345092,-1.337505,-0.454550,0.269328
12910,725,departure,active,isb,opis,2024-06-25 09:50:00,ruh,oerk,2024-06-25 10:45:00,25,...,0.712222,-1.086675,-1.148287,-0.916751,-0.329007,0.752770,0.993019,-1.337505,-0.728289,0.256905
12911,211,departure,active,isb,opis,2024-06-22 15:35:00,dxb,omdb,2024-06-22 15:58:00,22,...,0.712222,-0.523708,-0.776610,-0.428844,-0.567297,0.058780,-0.345092,-1.337505,-0.454550,0.256905
12912,207,departure,active,isb,opis,2024-06-19 17:00:00,khi,opkc,2024-06-19 18:00:00,19,...,0.515723,-1.579271,-1.340320,-0.862539,2.371611,1.472465,-0.345092,-1.777550,-1.002027,0.256905
12913,763,departure,active,isb,opis,2024-06-25 00:35:00,jed,oejn,2024-06-25 00:35:00,25,...,0.712222,-1.086675,-1.148287,-0.916751,-0.329007,0.752770,0.993019,-1.337505,-0.728289,0.256905

In [22]:
result2.to_csv("MergedTestData.csv",index=False)