In [5]:
from docx import Document
import numpy as np
import pandas as pd 
import json
import re
import os

In [6]:
def extractText(filename):
    doc = Document(filename)
    text = ""
    for paragraph in doc.paragraphs:
        text += paragraph.text.strip()
    cleaned_text = text.replace('\n', '').replace('\t', '')
    return json.loads(text)

def get_filenames(directory):
    filenames = os.listdir(directory)    
    return filenames

In [7]:
def flatten_and_convert_to_dataframe(data):
    flattened_data = []
    for entry in data:
        flat_entry = {
            "Flight Number": entry["flight"].get("number", np.nan),
            "Type": entry["type"],
            "Status": entry["status"],
            "Departure IATA Code": entry["departure"].get("iataCode", np.nan),
            "Departure ICAO Code": entry["departure"].get("icaoCode", np.nan),
            "Scheduled Time": entry["departure"].get("scheduledTime", np.nan),
            "Actual Time": entry["departure"].get("actualTime", np.nan),
            "Arrival IATA Code": entry["arrival"].get("iataCode", np.nan),
            "Arrival ICAO Code": entry["arrival"].get("icaoCode", np.nan),
            "Arrival Estimated Time": entry["arrival"].get("estimatedTime", np.nan)
        }
        flattened_data.append(flat_entry)
    return pd.DataFrame(flattened_data)

In [8]:
basePath = r'C:\Users\FARJAD FARHAT\Downloads\MLProject\ML-Proj-Dataset\Train'

names = get_filenames(basePath)
files = []
for i in names:
    print(i)
    out = extractText(os.path.join(basePath,i))
    files.append(out)

1.docx
10.docx
11.docx
12.docx
13.docx
14.docx
15.docx
16.docx
17.docx
18.docx
19.docx
2.docx
20.docx
21.docx
22.docx
23.docx
24.docx
25.docx
26.docx
27.docx
28.docx
29.docx
3.docx
30.docx
31.docx
32.docx
33.docx
34.docx
35.docx
36.docx
37.docx
39.docx
4.docx
40.docx
41.docx
42.docx
43.docx
44.docx
45.docx
46.docx
47.docx
48.docx
49.docx
5.docx
50.docx
51.docx
52.docx
53.docx
54.docx
55.docx
56.docx
57.docx
58.docx
59.docx
6.docx
60.docx
61.docx
62.docx
63.docx
64.docx
65.docx
66.docx
67.docx
68.docx
69.docx
7.docx
70.docx
71.docx
72.docx
8.docx
9.docx

In [9]:
dfs = [] 
for file in files :
    temp = flatten_and_convert_to_dataframe(file)
    dfs.append(temp)

In [10]:
df = pd.concat(dfs,axis=0,ignore_index=True)

In [11]:
df

,Flight Number,Type,Status,Departure IATA Code,Departure ICAO Code,Scheduled Time,Actual Time,Arrival IATA Code,Arrival ICAO Code,Arrival Estimated Time
0,737,departure,active,lhe,opla,2023-07-20t20:50:00.000,2023-07-20t20:15:00.000,ruh,oerk,2023-07-20t21:54:00.000
1,843,departure,active,lhe,opla,2023-07-18t15:05:00.000,NaN,khi,opkc,NaN
2,841,departure,active,lhe,opla,2023-07-23t09:50:00.000,NaN,khi,opkc,NaN
3,205,departure,active,lhe,opla,2023-07-26t23:30:00.000,2023-07-26t23:51:00.000,kwi,okkk,2023-07-27t01:24:00.000
4,723,departure,active,lhe,opla,2023-07-20t11:35:00.000,NaN,dxb,omdb,NaN
...,...,...,...,...,...,...,...,...,...,...
51567,841,departure,active,lhe,opla,2023-11-16t09:50:00.000,2023-11-16t10:03:00.000,khi,opkc,2023-11-16t11:34:00.000
51568,735,departure,active,lhe,opla,2023-11-16t11:40:00.000,2023-11-16t11:48:00.000,jed,oejn,2023-11-16t14:48:00.000
51569,203,departure,active,lhe,opla,2023-11-27t10:50:00.000,NaN,dxb,omdb,NaN
51570,898,departure,active,lhe,opla,2023-11-19t02:00:00.000,NaN,kul,wmkk,NaN
51571,731,departure,active,lhe,opla,2023-11-23t06:30:00.000,2023-11-23t06:47:00.000,jed,oejn,2023-11-23t10:00:00.000

In [12]:
columns = ['Scheduled Time','Actual Time','Arrival Estimated Time']
for col in columns:
    df[col] = pd.to_datetime(df[col], format='%Y-%m-%dT%H:%M:%S.%f', errors='coerce')

In [15]:
df['Days'] = df['Scheduled Time'].dt.day
df['Month'] = df['Scheduled Time'].dt.strftime('%b')
df['Year'] = df['Scheduled Time'].dt.year.astype(str)
df['Hour'] = df['Scheduled Time'].dt.hour
df

,Flight Number,Type,Status,Departure IATA Code,Departure ICAO Code,Scheduled Time,Actual Time,Arrival IATA Code,Arrival ICAO Code,Arrival Estimated Time,Days,Month,Year,Hour
0,737,departure,active,lhe,opla,2023-07-20 20:50:00,2023-07-20 20:15:00,ruh,oerk,2023-07-20 21:54:00,20,Jul,2023,20
1,843,departure,active,lhe,opla,2023-07-18 15:05:00,NaT,khi,opkc,NaT,18,Jul,2023,15
2,841,departure,active,lhe,opla,2023-07-23 09:50:00,NaT,khi,opkc,NaT,23,Jul,2023,9
3,205,departure,active,lhe,opla,2023-07-26 23:30:00,2023-07-26 23:51:00,kwi,okkk,2023-07-27 01:24:00,26,Jul,2023,23
4,723,departure,active,lhe,opla,2023-07-20 11:35:00,NaT,dxb,omdb,NaT,20,Jul,2023,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51567,841,departure,active,lhe,opla,2023-11-16 09:50:00,2023-11-16 10:03:00,khi,opkc,2023-11-16 11:34:00,16,Nov,2023,9
51568,735,departure,active,lhe,opla,2023-11-16 11:40:00,2023-11-16 11:48:00,jed,oejn,2023-11-16 14:48:00,16,Nov,2023,11
51569,203,departure,active,lhe,opla,2023-11-27 10:50:00,NaT,dxb,omdb,NaT,27,Nov,2023,10
51570,898,departure,active,lhe,opla,2023-11-19 02:00:00,NaT,kul,wmkk,NaT,19,Nov,2023,2
51571,731,departure,active,lhe,opla,2023-11-23 06:30:00,2023-11-23 06:47:00,jed,oejn,2023-11-23 10:00:00,23,Nov,2023,6

In [16]:
df.isnull().sum()

Flight Number                 0
Type                          0
Status                        0
Departure IATA Code           0
Departure ICAO Code           0
Scheduled Time                0
Actual Time               20582
Arrival IATA Code             0
Arrival ICAO Code             0
Arrival Estimated Time    21364
Days                          0
Month                         0
Year                          0
Hour                          0
dtype: int64

In [17]:
df

,Flight Number,Type,Status,Departure IATA Code,Departure ICAO Code,Scheduled Time,Actual Time,Arrival IATA Code,Arrival ICAO Code,Arrival Estimated Time,Days,Month,Year,Hour
0,737,departure,active,lhe,opla,2023-07-20 20:50:00,2023-07-20 20:15:00,ruh,oerk,2023-07-20 21:54:00,20,Jul,2023,20
1,843,departure,active,lhe,opla,2023-07-18 15:05:00,NaT,khi,opkc,NaT,18,Jul,2023,15
2,841,departure,active,lhe,opla,2023-07-23 09:50:00,NaT,khi,opkc,NaT,23,Jul,2023,9
3,205,departure,active,lhe,opla,2023-07-26 23:30:00,2023-07-26 23:51:00,kwi,okkk,2023-07-27 01:24:00,26,Jul,2023,23
4,723,departure,active,lhe,opla,2023-07-20 11:35:00,NaT,dxb,omdb,NaT,20,Jul,2023,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51567,841,departure,active,lhe,opla,2023-11-16 09:50:00,2023-11-16 10:03:00,khi,opkc,2023-11-16 11:34:00,16,Nov,2023,9
51568,735,departure,active,lhe,opla,2023-11-16 11:40:00,2023-11-16 11:48:00,jed,oejn,2023-11-16 14:48:00,16,Nov,2023,11
51569,203,departure,active,lhe,opla,2023-11-27 10:50:00,NaT,dxb,omdb,NaT,27,Nov,2023,10
51570,898,departure,active,lhe,opla,2023-11-19 02:00:00,NaT,kul,wmkk,NaT,19,Nov,2023,2
51571,731,departure,active,lhe,opla,2023-11-23 06:30:00,2023-11-23 06:47:00,jed,oejn,2023-11-23 10:00:00,23,Nov,2023,6

In [18]:
df.to_csv('Train.csv', index=False)